# Generated by Django 4.1.5 on 2023-02-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionapp', '0002_adddoctor_delete_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddoctor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adddoctor',
            name='fee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adddoctor',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='adddoctor',
            name='specialities',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adddoctor',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
