# Generated by Django 4.1.5 on 2023-02-15 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictionapp', '0008_remove_blood_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blood',
            old_name='bloodgroup',
            new_name='blood_group',
        ),
    ]
