# Generated by Django 4.1.5 on 2023-02-15 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictionapp', '0010_rename_blood_group_blood_bloodgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blood',
            old_name='mobile',
            new_name='mobilenumber',
        ),
    ]
