# Generated by Django 4.1.5 on 2023-04-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionapp', '0014_diseaseinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood',
            name='mobilenumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
