# Generated by Django 4.1.5 on 2023-04-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionapp', '0016_diseaseinfo_no_of_symp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaseinfo',
            name='no_of_symp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
