# Generated by Django 4.1.5 on 2023-04-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionapp', '0019_remove_diseaseinfo_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseaseinfo',
            name='confidence',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
