# Generated by Django 4.1.5 on 2023-04-24 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictionapp', '0021_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
