# Generated by Django 4.1.5 on 2023-04-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictionapp', '0022_delete_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaseinfo',
            name='confidence',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
